#pragma kernel CalculateWCSPHPressure
#pragma kernel UpdateWCSPHVelocities

#include "Common.hlsl"
#include "Partition.hlsl"
#include "Kernels.hlsl"
#include "Viscosity.hlsl"
#include "External.hlsl"
#include "Pressure.hlsl"
#include "WCSPH.hlsl"

[numthreads(NumThreads, 1, 1)]
void CalculateWCSPHPressure(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Pressures[id.x] = CalculateTaitPressure(id.x);
}

[numthreads(NumThreads, 1, 1)]
void UpdateWCSPHVelocities(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    float3 acceleration = CalculateWCSPHAcceleration(id.x);

    if (any(isnan(acceleration))) return;

    Velocities[id.x] += acceleration * deltaTime;
    float mag = length(Velocities[id.x]);
    if (mag > maxVelocity) {
        Velocities[id.x] = maxVelocity * Velocities[id.x] / mag;
    }
}
