using UnityEditor;
using UnityEngine;

class MarchingCubes
{
    Shader vertexShader;
    ShaderHelper computeShader;

    Bounds bounds;
    Mesh mesh;
    Material mat;
    ComputeBuffer argsBuffer;

    ComputeBuffer triangleBuffer;
    uint[] args = new uint[5] { 0, 0, 0, 0, 0 };

    int kernel;

    public MarchingCubes(Shader vertexShader, ComputeShader computeShader, Bounds bounds, Mesh mesh)
    {
        this.vertexShader = vertexShader;
        this.computeShader = new ShaderHelper(computeShader);
        this.bounds = bounds;
        this.mesh = mesh;
        mat = new Material(vertexShader);
        mat.enableInstancing = true;

        FindKernels(computeShader);
    }

    void InitialiseArgsBuffer(int instanceCount)
    {
        if (argsBuffer != null) argsBuffer.Release();

        argsBuffer = new ComputeBuffer(1, args.Length * sizeof(uint), ComputeBufferType.IndirectArguments);

        args[0] = mesh.GetIndexCount(0);
        args[1] = (uint)instanceCount;
        args[2] = mesh.GetIndexStart(0);
        args[3] = mesh.GetBaseVertex(0);
        argsBuffer.SetData(args);
    }

    void FindKernels(ComputeShader shader)
    {
        shader.FindKernel("ProcessVoxel");
    }

    void CreateTriangleBuffer(int maxTriangles)
    {
        int stride = System.Runtime.InteropServices.Marshal.SizeOf(typeof(Triangle));
        bool createNewBuffer = triangleBuffer == null || !triangleBuffer.IsValid() || triangleBuffer.count != maxTriangles || triangleBuffer.stride != stride;
        if (createNewBuffer)
        {
            triangleBuffer.Release();
            triangleBuffer = new ComputeBuffer(maxTriangles, stride, ComputeBufferType.Append);
        }

        triangleBuffer.SetCounterValue(0);
    }

    public ComputeBuffer Run(RenderTexture densityTex)
    {
        int numVoxels = densityTex.width * densityTex.height * densityTex.volumeDepth;
        
        // Most complex geometry generated by MC requires 5 triangles, no more
        int maxTriangles = numVoxels * 5;

        CreateTriangleBuffer(maxTriangles);
        CalculateTriangles(densityTex.width, densityTex.height, densityTex.volumeDepth);

        return triangleBuffer;
    }

    void CalculateTriangles(int voxelsX, int voxelsY, int voxelsZ)
    {
        int dispatchX = Mathf.CeilToInt(voxelsX / 8f);
        int dispatchY = Mathf.CeilToInt(voxelsY / 8f);
        int dispatchZ = Mathf.CeilToInt(voxelsZ / 8f);

        computeShader.Dispatch(kernel, dispatchX, dispatchY, dispatchZ);
    }

    public void BindPositions(ComputeBuffer positionBuffer)
    {
        mat.SetBuffer("positions", positionBuffer);
        InitialiseArgsBuffer(positionBuffer.count);
    }

    public void UpdateContainerSize(Vector3 containerSize)
    {
        mat.SetVector("containerSize", containerSize);
    }

    public void UpdateSize(float size)
    {
        mat.SetFloat("size", size);
    }

    public void DrawFrame(RenderTexture densityTex)
    {
        if (argsBuffer == null) return;

        mat.SetTexture("DensityTex", densityTex);

        Graphics.DrawMeshInstancedIndirect(
            mesh,
            0,
            mat,
            bounds,
            argsBuffer
        );
    }

    public void CleanupBuffers()
    {
        if (argsBuffer != null)
            argsBuffer.Release();
        if (triangleBuffer != null)
            triangleBuffer.Release();
    }

    public struct Vertex
    {
        public Vector3 pos;
        public Vector3 normal;
    }

    public struct Triangle
    {
        public Vertex a;
        public Vertex b;
        public Vertex c;
    }
}