using System.Linq;
using UnityEngine;

class MarchingCubes
{
    ComputeShader shader;

    ComputeBuffer argsBuffer;

    ComputeBuffer triangleBuffer;
    ComputeBuffer lutBuffer;

    int kernel;

    public MarchingCubes(ComputeShader shader)
    {
        this.shader = shader;

        FindKernels(shader);
        SetupBuffers();
    }

    void FindKernels(ComputeShader shader)
    {
        shader.FindKernel("ProcessCube");
    }

    void SetupBuffers()
    {
        string lutString = Resources.Load<TextAsset>("MarchingCubesLUT").text;
        int[] lutVals = lutString.Trim().Split(',').Select(x => int.Parse(x)).ToArray();

        lutBuffer = new ComputeBuffer(lutVals.Length, sizeof(int));

        shader.SetBuffer(kernel, "LUT", lutBuffer);
    }

    void CreateTriangleBuffer(int maxTriangles)
    {
        int stride = System.Runtime.InteropServices.Marshal.SizeOf(typeof(Triangle));
        bool createNewBuffer = triangleBuffer == null || !triangleBuffer.IsValid() || triangleBuffer.count != maxTriangles || triangleBuffer.stride != stride;
        if (createNewBuffer)
        {
            if (triangleBuffer != null) triangleBuffer.Release();
            triangleBuffer = new ComputeBuffer(maxTriangles, stride, ComputeBufferType.Append);
        }

        triangleBuffer.SetCounterValue(0);
    }

    public ComputeBuffer Run(RenderTexture densityTex, float isoLevel)
    {
        int numVoxels = densityTex.width * densityTex.height * densityTex.volumeDepth;
        
        // Most complex geometry generated by MC requires 5 triangles, no more
        int maxTriangles = numVoxels * 5;

        shader.SetTexture(kernel, "DensityTex", densityTex);
        shader.SetFloat("isoLevel", isoLevel);

        CreateTriangleBuffer(maxTriangles);
        shader.SetBuffer(kernel, "Triangles", triangleBuffer);
        
        // Voxel count on a side is 1 less than the resolution
        CalculateTriangles(densityTex.width - 1, densityTex.height - 1, densityTex.volumeDepth - 1);

        return triangleBuffer;
    }

    void CalculateTriangles(int voxelsX, int voxelsY, int voxelsZ)
    {
        shader.SetInts("densityTexDims", voxelsX + 1, voxelsY + 1, voxelsZ + 1);

        int dispatchX = Mathf.CeilToInt(voxelsX / 8f);
        int dispatchY = Mathf.CeilToInt(voxelsY / 8f);
        int dispatchZ = Mathf.CeilToInt(voxelsZ / 8f);

        shader.Dispatch(kernel, dispatchX, dispatchY, dispatchZ);
    }

    public void CleanupBuffers()
    {
        if (argsBuffer != null)
            argsBuffer.Release();
        if (triangleBuffer != null)
            triangleBuffer.Release();
        if (lutBuffer != null)
            lutBuffer.Release();
    }

    public struct Vertex
    {
        public Vector3 pos;
        public Vector3 normal;
    }

    public struct Triangle
    {
        public Vertex a;
        public Vertex b;
        public Vertex c;
    }
}