#pragma kernel DensityField

int instanceCount;
float smoothingRadiusSq;
float kernelConstant;
float kernelVolume;

RWStructuredBuffer<float2> Positions;

RWTexture2D<float4> Field;
int2 fieldSize;

float2 worldMin;
float2 worldMax;

float Kernel

float CalculateDensity(float2 pointWorld) {
    float density = 0;

    for (int i = 0; i < instanceCount; i++) {
        float2 offset = Positions[i] - pointWorld;
        density += SmoothingKernel(offset);
    }

    return density / kernelVolume;
}

float SmoothingKernel(float2 offset) {
    float oSquared = dot(offset, offset);
    if (dot(oSquared) > smoothingRadiusSq) return 0;

    float diff = smoothingRadiusSq - oSquared;

    return kernelConstant * diff * diff * diff;
}

[numthreads(8, 8, 1)]
void DensityField(uint3 id : SV_DispatchThreadID) {
    if (id.x >= fieldSize.x || id.y >= fieldSize.y) return;

    float2 uv = (float2(id.xy) + 0.5) / fieldSize;
    float2 pointWorld = lerp(worldMin, worldMax, uv);

    float density = CalculateDensity(pointWorld);

    Field[id.xy] = float4(value, 0, 0, 1);
}