#pragma kernel InitialisePressures
#pragma kernel CalculateNonPressureAccelerationAndD
#pragma kernel PredictVelocity
#pragma kernel PredictDensityAndCalculateA
#pragma kernel CalculatePressureSums
#pragma kernel CalculateNextIISPHPressure
#pragma kernel FinalisePressureIteration
#pragma kernel UpdateIISPHVelocities

RWStructuredBuffer<float> Aii;
RWStructuredBuffer<float> IterPressures;

RWStructuredBuffer<float3> Dii;
RWStructuredBuffer<float3> DPSum;

#include "Common.hlsl"
#include "Partition.hlsl"
#include "Kernels.hlsl"
#include "Viscosity.hlsl"
#include "Pressure.hlsl"
#include "External.hlsl"
#include "IISPH.hlsl"

[numthreads(NumThreads, 1, 1)]
void InitialisePressures(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    IterPressures[id.x] = 0;
}

[numthreads(NumThreads, 1, 1)]
void CalculateNonPressureAccelerationAndD(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    AccAndD accAndD = CalculateAccelerationAndD(id.x);
    IntermediateAccelerations[id.x] = accAndD.acceleration;
    Dii[id.x] = accAndD.D;
}

[numthreads(NumThreads, 1, 1)]
void PredictVelocity(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Velocities[id.x] += IntermediateAccelerations[id.x] * deltaTime;
    Velocities[id.x] = CollideVelocity(id.x);
}

[numthreads(NumThreads, 1, 1)]
void PredictDensityAndCalculateA(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    float density = Densities[3 * id.x];

    float2 values = CalculateDeltaDensityAndA(id.x, density);
    float deltaDensity = values.x;
    float a = values.y;

    Densities[3 * id.x + 2] = density + deltaDensity * deltaTime;
    Aii[id.x] = a;
}

[numthreads(NumThreads, 1, 1)]
void CalculatePressureSums(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    DPSum[id.x] = CalculatePressureSum(id.x);
}

[numthreads(NumThreads, 1, 1)]
void CalculateNextIISPHPressure(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Pressures[id.x] = CalculateNextIISPHPressureValue(id.x, Densities[3 * id.x]);
}

[numthreads(NumThreads, 1, 1)]
void FinalisePressureIteration(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    IterPressures[id.x] = Pressures[id.x];
}

[numthreads(NumThreads, 1, 1)]
void UpdateIISPHVelocities(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    float3 pressureForce = CalculateXSPHPressureForce(id.x);

    if (any(isnan(pressureForce))) return;

    Velocities[id.x] += pressureForce * deltaTime / particleMass;
    float mag = length(Velocities[id.x]);
    if (mag > maxVelocity) {
        Velocities[id.x] = maxVelocity * Velocities[id.x] / mag;
    }
}
