#pragma kernel ZeroCounts
#pragma kernel Partition
#pragma kernel Scan
#pragma kernel ScanBlockSums
#pragma kernel AddBlockSums
#pragma kernel FinalizeScan
#pragma kernel Scatter
#pragma kernel Density

#pragma kernel UpdateAccelerations
#pragma kernel UpdateVelocities
#pragma kernel UpdatePositions

static const uint NumThreads = 64;

RWStructuredBuffer<uint> CellCounts;
RWStructuredBuffer<uint> Offsets;
RWStructuredBuffer<uint> LocalOffsets;

RWStructuredBuffer<float2> Positions;

RWStructuredBuffer<float2> Velocities;

RWStructuredBuffer<float2> Accelerations;
RWStructuredBuffer<float2> OldAccelerations;

RWStructuredBuffer<float> Densities;

uint instanceCount;

float deltaTime;
float particleMass;

float smoothingRadius;

float2 containerSize;

uint tableSize;
uint numBlockSums;

#include "Helpers.hlsl"
#include "Partition.hlsl"
#include "Scan.hlsl"
#include "Scatter.hlsl"
#include "External.hlsl"
#include "Density.hlsl"
#include "Pressure.hlsl"
#include "Viscosity.hlsl"

[numthreads(NumThreads, 1, 1)]
void ZeroCounts(uint id : SV_DispatchThreadID) {
    if (id.x >= tableSize) return;

    CellCounts[id.x] = 0;
    LocalOffsets[id.x] = 0;
}

[numthreads(NumThreads, 1, 1)]
void Partition(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;
    IndexAndCount(id.x);
}

[numthreads(NumThreads, 1, 1)]
void Scan(uint3 id : SV_GroupThreadID, uint3 groupId : SV_GroupID) {
    PrefixScan(id.x, groupId.x);
}

[numthreads(NumThreads, 1, 1)]
void ScanBlockSums(uint3 id : SV_GroupThreadID) {
    ScanBlockSums(id.x, numBlockSums);
}

[numthreads(NumThreads, 1, 1)]
void AddBlockSums(uint3 id : SV_DispatchThreadID) {
    AddBlockSums(id.x);
}

[numthreads(1, 1, 1)]
void FinalizeScan(uint3 id : SV_DispatchThreadID) {
    Offsets[tableSize] = instanceCount;
}

[numthreads(NumThreads, 1, 1)]
void Scatter(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    SortParticle(id.x);
}

[numthreads(NumThreads, 1, 1)]
void Density(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Densities[id.x] = CalculateDensity(id.x);
}

[numthreads(NumThreads, 1, 1)]
void UpdateAccelerations(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    float2 external = gravity + MouseForce(id.x);
    float2 pressure = CalculatePressureForce(id.x);
    float2 viscosity = CalculateViscosityForce(id.x);

    Accelerations[id.x] = external + pressure + viscosity;
}

[numthreads(NumThreads, 1, 1)]
void UpdateVelocities(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Velocities[id.x] += deltaTime * ((OldAccelerations[id.x] + Accelerations[id.x]) / 2);
}

[numthreads(NumThreads, 1, 1)]
void UpdatePositions(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Positions[id.x] += Velocities[id.x] * deltaTime + 0.5 * Accelerations[id.x] * deltaTime * deltaTime;

    Collisions(id.x);
}