#pragma kernel ZeroCounts
#pragma kernel Partition
#pragma kernel Gravity
#pragma kernel Density
#pragma kernel Pressure
#pragma kernel Viscosity
#pragma kernel UpdatePositions

static const uint NumThreads = 64;

RWStructuredBuffer<uint> GridIndices;
RWStructuredBuffer<uint> CellCounts;

RWStructuredBuffer<float2> Positions;
RWStructuredBuffer<float2> PredictedPositions;
RWStructuredBuffer<float2> Velocities;
RWStructuredBuffer<float> Densities;

uint instanceCount;

float deltaTime;
float particleMass;

float smoothingRadius;

float2 containerSize;

#include "External.hlsl"
#include "Density.hlsl"
#include "Pressure.hlsl"
#include "Viscosity.hlsl"
#include "Partition.hlsl"

[numthreads(NumThreads, 1, 1)]
void ZeroCounts(uint id : SV_DispatchThreadID) {
    if (id.x >= tableSize) return;

    CellCounts[id.x] = 0;
}

[numthreads(NumThreads, 1, 1)]
void Partition(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;
    IndexAndCount(id.x);
}

[numthreads(NumThreads, 1, 1)]
void Gravity(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    // Classic Euler stuff
    Velocities[id.x] += gravity * deltaTime;

    PredictedPositions[id.x] = Positions[id.x] + Velocities[id.x] * deltaTime;
}

[numthreads(NumThreads, 1, 1)]
void Density(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Densities[id.x] = CalculateDensity(id.x);
}

[numthreads(NumThreads, 1, 1)]
void Pressure(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Velocities[id.x] += CalculatePressureForce(id.x) * deltaTime;
}

[numthreads(NumThreads, 1, 1)]
void Viscosity(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Velocities[id.x] += CalculateViscosityForce(id.x) * deltaTime;
}

[numthreads(NumThreads, 1, 1)]
void UpdatePositions(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Positions[id.x] += Velocities[id.x] * deltaTime;
    ApplyMouseForce(id.x);

    Collisions(id.x);
}