#pragma kernel ClearCounts
#pragma kernel Partition
#pragma kernel Scan
#pragma kernel ScanBlockSums
#pragma kernel ScanSuperBlockSums
#pragma kernel AddSuperBlockSums
#pragma kernel AddBlockSums
#pragma kernel FinalizeScan
#pragma kernel Scatter
#pragma kernel CopyBack

RWStructuredBuffer<uint> CellCounts;
RWStructuredBuffer<uint> Offsets;
RWStructuredBuffer<uint> LocalOffsets;

RWStructuredBuffer<float3> Positions;
RWStructuredBuffer<float3> SortedPositions;
RWStructuredBuffer<float3> Velocities;
RWStructuredBuffer<float3> SortedVelocities;

uint instanceCount;
uint tableSize;
uint numBlockSums;
uint numSuperBlocks;

float smoothingRadius;

float3 containerSize;

#include "Constants.hlsl"
#include "Partition.hlsl"
#include "Scan.hlsl"
#include "Scatter.hlsl"

[numthreads(NumThreads, 1, 1)]
void ClearCounts(uint id : SV_DispatchThreadID) {
    if (id.x >= tableSize) return;

    CellCounts[id.x] = 0;
    LocalOffsets[id.x] = 0;
}

[numthreads(NumThreads, 1, 1)]
void Partition(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;
    
    InterlockedAdd(CellCounts[CalculateHash(Positions[id.x])], 1);
}

[numthreads(NumThreads, 1, 1)]
void Scan(uint3 id : SV_GroupThreadID, uint3 groupId : SV_GroupID) {
    PrefixScan(id.x, groupId.x);
}

[numthreads(NumThreads, 1, 1)]
void ScanBlockSums(uint3 id : SV_GroupThreadID, uint3 groupId : SV_GroupID) {
    ScanBlockSums(id.x, numBlockSums, groupId.x);
}

[numthreads(NumThreads, 1, 1)]
void ScanSuperBlockSums(uint3 id : SV_GroupThreadID) {
    ScanSuperBlockSums(id.x, numSuperBlocks);
}

[numthreads(NumThreads, 1, 1)]
void AddSuperBlockSums(uint3 id : SV_DispatchThreadID) {
    AddSuperBlockSums(id.x, numBlockSums);
}

[numthreads(NumThreads, 1, 1)]
void AddBlockSums(uint3 id : SV_DispatchThreadID) {
    AddBlockSums(id.x);
}

[numthreads(1, 1, 1)]
void FinalizeScan(uint3 id : SV_DispatchThreadID) {
    Offsets[tableSize] = instanceCount;
}

[numthreads(NumThreads, 1, 1)]
void Scatter(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    SortParticle(id.x);
}

[numthreads(NumThreads, 1, 1)]
void CopyBack(uint3 id : SV_DispatchThreadID) {
    if (id.x >= instanceCount) return;

    Velocities[id.x] = SortedVelocities[id.x];
    Positions[id.x] = SortedPositions[id.x];
}